# -*- coding: utf-8 -*-
"""Virtual Try-On.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDj98lvpHb4B7JiR_NrDxOuhVTEJJaqE
"""

from PIL import Image

def load_image(image_path):
    return Image.open(image_path).convert("RGBA")

def resize_clothing_to_user(user_image, clothing_image):
    clothing_resized = clothing_image.resize((user_image.width, int(user_image.height / 2)))
    return clothing_resized

def virtual_try_on(user_image, clothing_image):
    clothing_resized = resize_clothing_to_user(user_image, clothing_image)
    user_image = user_image.convert("RGBA")
    clothing_resized = clothing_resized.convert("RGBA")
    result_image = Image.new("RGBA", user_image.size)
    position = (0, int(user_image.height / 3))
    result_image.paste(user_image, (0, 0), user_image)
    result_image.paste(clothing_resized, position, clothing_resized)
    return result_image


# Load user and clothing images
user_image = load_image('image.png')
clothing_image = load_image('clothing.png')

result_image = virtual_try_on(user_image, clothing_image)

result_image.show()
result_image.save('virtual_try_on_result.png')